export const data = [
  { id: 1, first_name: 'Jesse', last_name: 'Simmons', date: '2016-10-15', gender: 'Male' },
  { id: 2, first_name: 'John', last_name: 'Jacobs', date: '2016-12-15', gender: 'Male' },
  { id: 3, first_name: 'Tina', last_name: 'Gilbert', date: '2016-04-26', gender: 'Female' },
  { id: 4, first_name: 'Clarence', last_name: 'Flores', date: '2016-04-10', gender: 'Male' },
  { id: 5, first_name: 'Anne', last_name: 'Lee', date: '2016-12-06', gender: 'Female' },
];

export const columns = [
  {
    field: 'id',
    label: 'ID',
  },
  {
    field: 'first_name',
    label: 'First Name',
  },
  {
    field: 'last_name',
    label: 'Last Name',
  },
  {
    field: 'date',
    label: 'Date',
  },
  {
    field: 'gender',
    label: 'Gender',
  },
];

export const columnsSorting = [
  {
    field: 'id',
    label: 'ID',
    sortable: true,
  },
  {
    field: 'first_name',
    label: 'First Name',
    sortable: true,
  },
  {
    field: 'last_name',
    label: 'Last Name',
    sortable: true,
  },
  {
    field: 'date',
    label: 'Date',
    sortable: true,
  },
  {
    field: 'gender',
    label: 'Gender',
  },
];

export const columnsEdit = [
  {
    field: 'id',
    label: 'ID',
    visible: true,
  },
  {
    field: 'first_name',
    label: 'First Name',
    visible: true,
  },
  {
    field: 'last_name',
    label: 'Last Name',
    visible: true,
  },
  {
    field: 'date',
    label: 'Date',
    visible: true,
  },
  {
    field: 'gender',
    label: 'Gender',
    visible: true,
  },
];

export const columnsBig = [
  {
    field: 'id',
    label: 'ID',
  },
  {
    field: 'first_name',
    label: 'First Name',
  },
  {
    field: 'last_name',
    label: 'Last Name',
  },
  {
    field: 'street',
    label: 'Street',
  },
  {
    field: 'date',
    label: 'Date',
  },
  {
    field: 'gender',
    label: 'Gender',
  },
];

export const dataBig = [
  {
    id: 1,
    first_name: 'Matt',
    last_name: 'Oglevie',
    street: '160 Emmet Point',
    date: '9/6/2019',
    gender: 'Male',
  },
  {
    id: 2,
    first_name: 'Myrna',
    last_name: 'Kinzel',
    street: '9056 Bayside Drive',
    date: '8/25/2020',
    gender: 'Female',
  },
  {
    id: 3,
    first_name: 'Brandy',
    last_name: 'Goodbar',
    street: '3439 Northland Alley',
    date: '2/6/2020',
    gender: 'Male',
  },
  {
    id: 4,
    first_name: 'Hayden',
    last_name: 'Pretty',
    street: '169 Lakewood Gardens Junction',
    date: '4/11/2020',
    gender: 'Male',
  },
  {
    id: 5,
    first_name: 'Padriac',
    last_name: 'Latchmore',
    street: '5 Golf View Circle',
    date: '1/18/2020',
    gender: 'Male',
  },
  {
    id: 6,
    first_name: 'Celka',
    last_name: 'Emanuelli',
    street: '0 Superior Road',
    date: '4/9/2020',
    gender: 'Female',
  },
  {
    id: 7,
    first_name: 'Saunders',
    last_name: 'Igounet',
    street: '5 Jackson Park',
    date: '5/10/2020',
    gender: 'Male',
  },
  {
    id: 8,
    first_name: 'Anna',
    last_name: 'Allderidge',
    street: '905 International Hill',
    date: '7/22/2020',
    gender: 'Female',
  },
  {
    id: 9,
    first_name: 'Ingelbert',
    last_name: 'Bateson',
    street: '4 Valley Edge Trail',
    date: '12/31/2019',
    gender: 'Male',
  },
  {
    id: 10,
    first_name: 'Jon',
    last_name: 'Iacomettii',
    street: '297 Dunning Court',
    date: '12/17/2019',
    gender: 'Male',
  },
  {
    id: 11,
    first_name: 'Jasen',
    last_name: 'Proppers',
    street: '639 Shoshone Circle',
    date: '12/4/2019',
    gender: 'Male',
  },
  {
    id: 12,
    first_name: 'Fredia',
    last_name: 'Chesswas',
    street: '11 Manufacturers Way',
    date: '3/26/2020',
    gender: 'Female',
  },
  {
    id: 13,
    first_name: 'Tyne',
    last_name: 'Feehily',
    street: '22 Fuller Hill',
    date: '6/11/2020',
    gender: 'Female',
  },
  {
    id: 14,
    first_name: 'Raphael',
    last_name: 'McTrustie',
    street: '08009 Farmco Hill',
    date: '4/18/2020',
    gender: 'Male',
  },
  {
    id: 15,
    first_name: 'Elihu',
    last_name: 'Loughead',
    street: '6 Gina Hill',
    date: '8/23/2020',
    gender: 'Male',
  },
  {
    id: 16,
    first_name: 'Lyndsay',
    last_name: 'Duddle',
    street: '902 Veith Road',
    date: '6/15/2020',
    gender: 'Female',
  },
  {
    id: 17,
    first_name: 'Dexter',
    last_name: 'Kob',
    street: '76901 Maple Parkway',
    date: '12/2/2019',
    gender: 'Male',
  },
  {
    id: 18,
    first_name: 'Mia',
    last_name: 'Pharro',
    street: '25 Walton Trail',
    date: '8/10/2020',
    gender: 'Female',
  },
  {
    id: 19,
    first_name: 'Lynnette',
    last_name: 'Jaggard',
    street: '1407 Westend Avenue',
    date: '11/10/2019',
    gender: 'Female',
  },
  {
    id: 20,
    first_name: 'Thane',
    last_name: "O'Growgane",
    street: '514 Summerview Point',
    date: '9/26/2019',
    gender: 'Male',
  },
  {
    id: 21,
    first_name: 'Idalina',
    last_name: 'Piborn',
    street: '25753 Milwaukee Pass',
    date: '7/20/2020',
    gender: 'Female',
  },
  {
    id: 22,
    first_name: 'Don',
    last_name: 'Camm',
    street: '96062 Pleasure Parkway',
    date: '4/11/2020',
    gender: 'Male',
  },
  {
    id: 23,
    first_name: 'Danit',
    last_name: 'Mackin',
    street: '44 Clove Road',
    date: '5/1/2020',
    gender: 'Female',
  },
  {
    id: 24,
    first_name: 'Reta',
    last_name: 'Imlen',
    street: '7 Superior Way',
    date: '5/10/2020',
    gender: 'Female',
  },
  {
    id: 25,
    first_name: 'Tillie',
    last_name: 'Clemente',
    street: '421 Buhler Point',
    date: '11/11/2019',
    gender: 'Female',
  },
  {
    id: 26,
    first_name: 'Mendy',
    last_name: 'Bullene',
    street: '4 Canary Court',
    date: '4/15/2020',
    gender: 'Male',
  },
  {
    id: 27,
    first_name: 'Vladamir',
    last_name: 'Hamfleet',
    street: '49 Golf View Street',
    date: '9/28/2019',
    gender: 'Male',
  },
  {
    id: 28,
    first_name: 'Marsha',
    last_name: 'Rubberts',
    street: '93 Colorado Court',
    date: '4/19/2020',
    gender: 'Female',
  },
  {
    id: 29,
    first_name: 'Vern',
    last_name: 'Josuweit',
    street: '1 Trailsway Avenue',
    date: '3/30/2020',
    gender: 'Male',
  },
  {
    id: 30,
    first_name: 'Paulie',
    last_name: "O'Currine",
    street: '2 Mifflin Alley',
    date: '4/20/2020',
    gender: 'Male',
  },
  {
    id: 31,
    first_name: 'Martha',
    last_name: 'Goscar',
    street: '4 International Center',
    date: '10/2/2019',
    gender: 'Female',
  },
  {
    id: 32,
    first_name: 'Flossy',
    last_name: 'Haughin',
    street: '8732 Becker Alley',
    date: '2/21/2020',
    gender: 'Female',
  },
  {
    id: 33,
    first_name: 'Bradan',
    last_name: 'Pratt',
    street: '76149 Old Gate Place',
    date: '9/9/2019',
    gender: 'Male',
  },
  {
    id: 34,
    first_name: 'Yankee',
    last_name: 'Tyreman',
    street: '3 Carey Alley',
    date: '6/2/2020',
    gender: 'Male',
  },
  {
    id: 35,
    first_name: 'Natalya',
    last_name: 'Sawtell',
    street: '78 Commercial Center',
    date: '4/2/2020',
    gender: 'Female',
  },
  {
    id: 36,
    first_name: 'Ynez',
    last_name: 'Danell',
    street: '97 Sunnyside Junction',
    date: '2/12/2020',
    gender: 'Female',
  },
  {
    id: 37,
    first_name: 'Laural',
    last_name: 'Dust',
    street: '5916 Scoville Parkway',
    date: '9/16/2019',
    gender: 'Female',
  },
  {
    id: 38,
    first_name: 'Catriona',
    last_name: 'Nel',
    street: '7361 Pond Court',
    date: '1/12/2020',
    gender: 'Female',
  },
  {
    id: 39,
    first_name: 'Heather',
    last_name: 'Kleinzweig',
    street: '7525 Iowa Terrace',
    date: '5/31/2020',
    gender: 'Female',
  },
  {
    id: 40,
    first_name: 'Lanny',
    last_name: 'Flippini',
    street: '158 Buena Vista Way',
    date: '10/12/2019',
    gender: 'Female',
  },
  {
    id: 41,
    first_name: 'Kaia',
    last_name: 'Linke',
    street: '9085 Eastwood Road',
    date: '7/29/2020',
    gender: 'Female',
  },
  {
    id: 42,
    first_name: 'Granny',
    last_name: 'Fasey',
    street: '0694 Truax Terrace',
    date: '4/14/2020',
    gender: 'Male',
  },
  {
    id: 43,
    first_name: 'Gregoor',
    last_name: 'Learmonth',
    street: '95 Morningstar Terrace',
    date: '9/20/2019',
    gender: 'Male',
  },
  {
    id: 44,
    first_name: 'Kathie',
    last_name: 'Welham',
    street: '1515 Jay Crossing',
    date: '12/6/2019',
    gender: 'Female',
  },
  {
    id: 45,
    first_name: 'Rhetta',
    last_name: 'Valens-Smith',
    street: '992 Hauk Crossing',
    date: '11/27/2019',
    gender: 'Female',
  },
  {
    id: 46,
    first_name: 'Barnard',
    last_name: 'Blayd',
    street: '7866 Valley Edge Alley',
    date: '10/8/2019',
    gender: 'Male',
  },
  {
    id: 47,
    first_name: 'Ninette',
    last_name: 'Gounet',
    street: '59456 Merchant Center',
    date: '4/19/2020',
    gender: 'Female',
  },
  {
    id: 48,
    first_name: 'Sven',
    last_name: 'Ibbeson',
    street: '9 Bunker Hill Junction',
    date: '1/12/2020',
    gender: 'Male',
  },
  {
    id: 49,
    first_name: 'Breena',
    last_name: 'Kinnear',
    street: '08631 Sullivan Street',
    date: '3/20/2020',
    gender: 'Female',
  },
  {
    id: 50,
    first_name: 'Tasia',
    last_name: 'Leyburn',
    street: '3 Haas Junction',
    date: '12/10/2019',
    gender: 'Female',
  },
  {
    id: 51,
    first_name: 'Pennie',
    last_name: 'Gillum',
    street: '4 Lakewood Court',
    date: '8/27/2019',
    gender: 'Female',
  },
  {
    id: 52,
    first_name: 'Gale',
    last_name: 'Bleyman',
    street: '96862 Cardinal Plaza',
    date: '7/25/2020',
    gender: 'Male',
  },
  {
    id: 53,
    first_name: 'Caryl',
    last_name: 'Tiltman',
    street: '74804 Boyd Way',
    date: '7/26/2020',
    gender: 'Male',
  },
  {
    id: 54,
    first_name: 'Reider',
    last_name: 'Youles',
    street: '5985 Talisman Crossing',
    date: '11/2/2019',
    gender: 'Male',
  },
  {
    id: 55,
    first_name: 'Basil',
    last_name: 'Fannon',
    street: '1 Talmadge Parkway',
    date: '7/8/2020',
    gender: 'Male',
  },
  {
    id: 56,
    first_name: 'Ilise',
    last_name: 'McConway',
    street: '65 Bobwhite Alley',
    date: '9/8/2019',
    gender: 'Female',
  },
  {
    id: 57,
    first_name: 'Vita',
    last_name: 'Figiovanni',
    street: '623 Londonderry Street',
    date: '10/29/2019',
    gender: 'Female',
  },
  {
    id: 58,
    first_name: 'Kimberlyn',
    last_name: 'Marking',
    street: '75911 Holmberg Terrace',
    date: '6/11/2020',
    gender: 'Female',
  },
  {
    id: 59,
    first_name: 'Davon',
    last_name: 'Edden',
    street: '8842 Banding Hill',
    date: '3/25/2020',
    gender: 'Male',
  },
  {
    id: 60,
    first_name: 'Falkner',
    last_name: 'Slingsby',
    street: '462 Mcguire Avenue',
    date: '1/26/2020',
    gender: 'Male',
  },
  {
    id: 61,
    first_name: 'Decca',
    last_name: 'Maddyson',
    street: '99474 Monterey Terrace',
    date: '7/31/2020',
    gender: 'Male',
  },
  {
    id: 62,
    first_name: 'Daisie',
    last_name: 'Jeffry',
    street: '6 Grim Terrace',
    date: '5/19/2020',
    gender: 'Female',
  },
  {
    id: 63,
    first_name: 'Geri',
    last_name: 'Jeffreys',
    street: '401 Knutson Trail',
    date: '5/23/2020',
    gender: 'Female',
  },
  {
    id: 64,
    first_name: 'Eulalie',
    last_name: 'Whooley',
    street: '469 Rockefeller Junction',
    date: '1/16/2020',
    gender: 'Female',
  },
  {
    id: 65,
    first_name: 'Hugh',
    last_name: 'Bacop',
    street: '0806 Rowland Point',
    date: '10/15/2019',
    gender: 'Male',
  },
  {
    id: 66,
    first_name: 'Gayel',
    last_name: 'Cossell',
    street: '69 Onsgard Court',
    date: '2/1/2020',
    gender: 'Female',
  },
  {
    id: 67,
    first_name: 'Hinze',
    last_name: 'Tokell',
    street: '845 Graceland Avenue',
    date: '3/7/2020',
    gender: 'Male',
  },
  {
    id: 68,
    first_name: 'Annice',
    last_name: 'Ranyelld',
    street: '90028 Emmet Trail',
    date: '5/20/2020',
    gender: 'Female',
  },
  {
    id: 69,
    first_name: 'Ned',
    last_name: 'Swinney',
    street: '739 Annamark Road',
    date: '7/19/2020',
    gender: 'Male',
  },
  {
    id: 70,
    first_name: 'Sayers',
    last_name: 'McCaughey',
    street: '721 Donald Way',
    date: '2/16/2020',
    gender: 'Male',
  },
  {
    id: 71,
    first_name: 'Giraud',
    last_name: 'Chessman',
    street: '4 Doe Crossing Way',
    date: '9/13/2019',
    gender: 'Male',
  },
  {
    id: 72,
    first_name: 'Winifield',
    last_name: 'Bolletti',
    street: '46393 Kinsman Center',
    date: '9/24/2019',
    gender: 'Male',
  },
  {
    id: 73,
    first_name: 'Maurene',
    last_name: 'Clayson',
    street: '0947 Shelley Park',
    date: '5/13/2020',
    gender: 'Female',
  },
  {
    id: 74,
    first_name: 'Annabelle',
    last_name: 'Zylberdik',
    street: '451 Anniversary Road',
    date: '6/15/2020',
    gender: 'Female',
  },
  {
    id: 75,
    first_name: 'Melisse',
    last_name: 'Petraitis',
    street: '3956 Homewood Pass',
    date: '10/20/2019',
    gender: 'Female',
  },
  {
    id: 76,
    first_name: 'Jere',
    last_name: 'Mongin',
    street: '1739 Fairview Alley',
    date: '3/18/2020',
    gender: 'Female',
  },
  {
    id: 77,
    first_name: 'Baird',
    last_name: 'McCard',
    street: '3775 Northwestern Point',
    date: '8/28/2019',
    gender: 'Male',
  },
  {
    id: 78,
    first_name: 'Harlen',
    last_name: 'Roundtree',
    street: '245 Knutson Crossing',
    date: '5/15/2020',
    gender: 'Male',
  },
  {
    id: 79,
    first_name: 'Thomas',
    last_name: 'Durek',
    street: '23 Monterey Circle',
    date: '7/30/2020',
    gender: 'Male',
  },
  {
    id: 80,
    first_name: 'Leonore',
    last_name: 'Connue',
    street: '93 Buena Vista Circle',
    date: '6/6/2020',
    gender: 'Female',
  },
  {
    id: 81,
    first_name: 'Madelyn',
    last_name: 'Arntzen',
    street: '727 Mariners Cove Circle',
    date: '3/27/2020',
    gender: 'Female',
  },
  {
    id: 82,
    first_name: 'Pat',
    last_name: 'Andrei',
    street: '8 Kennedy Junction',
    date: '2/8/2020',
    gender: 'Female',
  },
  {
    id: 83,
    first_name: 'Olenolin',
    last_name: 'Vondrach',
    street: '888 Gina Lane',
    date: '11/4/2019',
    gender: 'Male',
  },
  {
    id: 84,
    first_name: 'Hanson',
    last_name: 'Girtin',
    street: '5351 Butternut Alley',
    date: '8/22/2020',
    gender: 'Male',
  },
  {
    id: 85,
    first_name: 'Idette',
    last_name: 'Vacher',
    street: '2 Cascade Circle',
    date: '3/21/2020',
    gender: 'Female',
  },
  {
    id: 86,
    first_name: 'Myrtia',
    last_name: 'Baulcombe',
    street: '6 Troy Drive',
    date: '8/9/2020',
    gender: 'Female',
  },
  {
    id: 87,
    first_name: 'Rocky',
    last_name: 'Benneyworth',
    street: '2564 7th Point',
    date: '3/3/2020',
    gender: 'Male',
  },
  {
    id: 88,
    first_name: 'Netti',
    last_name: 'Abrahamsen',
    street: '10 1st Lane',
    date: '11/23/2019',
    gender: 'Female',
  },
  {
    id: 89,
    first_name: 'Obadiah',
    last_name: 'Moquin',
    street: '9 Tony Point',
    date: '8/12/2020',
    gender: 'Male',
  },
  {
    id: 90,
    first_name: 'Crin',
    last_name: 'Sabie',
    street: '548 7th Road',
    date: '12/6/2019',
    gender: 'Female',
  },
  {
    id: 91,
    first_name: 'Mile',
    last_name: 'Kibbel',
    street: '6767 Cottonwood Court',
    date: '7/28/2020',
    gender: 'Male',
  },
  {
    id: 92,
    first_name: 'Lynne',
    last_name: 'Tildesley',
    street: '53811 Schiller Hill',
    date: '5/2/2020',
    gender: 'Female',
  },
  {
    id: 93,
    first_name: 'Orelia',
    last_name: 'Noods',
    street: '81 Messerschmidt Road',
    date: '12/2/2019',
    gender: 'Female',
  },
  {
    id: 94,
    first_name: 'Vivyanne',
    last_name: 'Rodolf',
    street: '01369 Gina Crossing',
    date: '1/10/2020',
    gender: 'Female',
  },
  {
    id: 95,
    first_name: 'Cassondra',
    last_name: 'Palay',
    street: '634 Sheridan Circle',
    date: '4/13/2020',
    gender: 'Female',
  },
  {
    id: 96,
    first_name: 'Ingrid',
    last_name: 'Liffe',
    street: '862 Sauthoff Court',
    date: '10/29/2019',
    gender: 'Female',
  },
  {
    id: 97,
    first_name: 'Aldous',
    last_name: 'Perse',
    street: '8 Badeau Junction',
    date: '5/5/2020',
    gender: 'Male',
  },
  {
    id: 98,
    first_name: 'Ree',
    last_name: 'Rosenbloom',
    street: '6562 Oxford Lane',
    date: '2/5/2020',
    gender: 'Female',
  },
  {
    id: 99,
    first_name: 'Kelsi',
    last_name: 'Ridett',
    street: '061 Starling Lane',
    date: '4/16/2020',
    gender: 'Female',
  },
  {
    id: 100,
    first_name: 'Lonnie',
    last_name: 'Dodge',
    street: '475 Esker Court',
    date: '6/29/2020',
    gender: 'Female',
  },
];
