#!/bin/bash
ASCIIDOCTOR_BIN=`command -v asciidoctor`
PANDOC_BIN=`command -v pandoc`

if [ ! -x $ASCIIDOCTOR_BIN ] || [ -z $ASCIIDOCTOR_BIN ]; then
  echo "Installing AsciiDoctor..."
  sudo apt install asciidoctor
  ASCIIDOCTOR_BIN=`command -v asciidoctor`
fi
if [ ! -x $PANDOC_BIN ] || [ -z $PANDOC_BIN ]; then
  echo "Installing PanDOC..."
  wget https://github.com/jgm/pandoc/releases/download/2.0.0.1/pandoc-2.0.0.1-1-amd64.deb
  sudo dpkg -i pandoc-2.0.0.1-1-amd64.deb
  rm pandoc-*.deb
  PANDOC_BIN=`command -v pandoc`
fi

$ASCIIDOCTOR_BIN -b docbook ./README.adoc
$PANDOC_BIN -f docbook -t gfm ./README.xml -o ./README.md